#! /bin/bash

printf "Delete an active user\n"
printf "\nCurrent users:\n"

awk -F':' '{if ($3 >= 1000 && $3 <= 60000) print $1}' /etc/passwd

printf "\nEnter a username to delete, or 'exit' to exit:\n"
read username

if [ $username == 'exit' ]
then
	printf "Exiting, goodbye!\n"
	exit
fi

found=$(awk -F: '{if ($3 >= 1000 && $3 <= 60000) print $1}' /etc/passwd | grep -w $username)

if [ -z $found ]
then
	printf "ERROR, username '$username' not found!\n"
else
	sudo userdel -f $username
fi
